version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Dockerfiles/nginx/SSL/server.crt:/etc/ssl/server.crt
      - ./Dockerfiles/nginx/SSL/server.key:/etc/ssl/server.key
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./Dockerfiles/frontend
    volumes:
      - ./Dockerfiles/frontend/www/src:/usr/src/app
      - ./logs/frontend/httpd:/var/logs/httpd
    #ports:
    #  - "8081:3000"
    links:
      - backend
  backend:
    build: ./Dockerfiles/backend
    volumes:
      - ./Dockerfiles/backend/www:/var/www/html
      - ./logs/backend/httpd:/var/logs/httpd
    #ports:
    #  - "8082:80"
    links:
      - "database"
      - "redis"
    depends_on:
      - database
      - redis
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: problemthree
    ports:
      - "3306:3306"
  redis:
    build: ./Dockerfiles/redis