version: '3'
services:
  frontend:
    build: ./Dockerfiles/frontend
    volumes:
      - ./Dockerfiles/frontend/www/src:/usr/src/app
      - ./logs/frontend/httpd:/var/logs/httpd
    ports:
      - "8080:3000"
    links:
      - backend
  backend:
    build: ./Dockerfiles/backend
    volumes:
      - ./Dockerfiles/backend/www:/var/www/html
      - ./logs/backend/httpd:/var/logs/httpd
    ports:
      - "80:80"
    links:
      - "database"
      - "redis"
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: problemthree
    ports:
      - 3306 #- "9906:3306"
  redis:
    build: ./Dockerfiles/redis